import { speechText, voiceControllerMover } from './MusicLogic';

let talkingOn = false;
let speechVolume = 0.2;
let speechPitch = 1;
let waitTime = 4000;

export const changeSpeechVolume = (newVolume, newPitch) => {
  console.log(newVolume);
  //waitTime = newVolume * 100;
  const newNewPitch = Math.floor(newPitch) * 0.004;

  if (newNewPitch < 0) {
    speechPitch = 0;
  } else if (newNewPitch > 2) {
    speechPitch = 2;
  } else {
    speechPitch = newNewPitch;
  }
};

const speaker = window.speechSynthesis;
const speak = () => {
  if (talkingOn) {
    let theSentence = newSentence();
    let utterance = new SpeechSynthesisUtterance(theSentence);
    utterance.lang = 'en-US';
    utterance.volume = speechVolume;
    utterance.pitch = speechPitch;
    let voices = speechSynthesis.getVoices();
    let englishSpeakers = [];
    let notEnglish = [];
    for (let i = 0; i < voices.length; i++) {
      if (voices[i].lang[0] === 'e' && voices[i].lang[1] === 'n') {
        englishSpeakers.push(voices[i]);
      } else {
        notEnglish.push(voices[i]);
      }
    }
    let randomSpeaker = Math.floor(Math.random() * 5);
    if (randomSpeaker === 1) {
      utterance.voice = notEnglish[Math.floor(Math.random() * notEnglish.length)];
    } else {
      utterance.voice = englishSpeakers[Math.floor(Math.random() * englishSpeakers.length)];
    }
    speaker.speak(utterance);
    speechText(theSentence);
    //utterance.onend = function funk(event) {
    //  voices = null;
    //  englishSpeakers = null;
    //  notEnglish = null;
    //  randomSpeaker = null;

    if (talkingOn) {
      setTimeout(speak, waitTime);
    }
    //utterance.removeEventListener('end', funk);
    utterance = null;
    //};
    console.log(utterance);

    console.log(speaker.speaking);
  }
};

export const turnSpeakingOn = () => {
  voiceControllerMover();
  if (talkingOn) {
    talkingOn = false;
  } else {
    talkingOn = true;
    speak();
  }
};

const newSentence = () => {
  let adverbsOnorOff = Math.floor(Math.random() * 26);
  if (adverbsOnorOff < 2) {
    let firstWord = subjects[Math.floor(Math.random() * subjects.length)];
    let secondWord = adverbs[Math.floor(Math.random() * adverbs.length)];
    let thirdWord = verbs[Math.floor(Math.random() * verbs.length)];
    let fourthWord = objects[Math.floor(Math.random() * objects.length)];
    let fullSentence = ` ${firstWord} ${secondWord} ${thirdWord} ${fourthWord}.`;
    return fullSentence;
  } else if (adverbsOnorOff >= 2 && adverbsOnorOff < 5) {
    let firstWord = subjects[Math.floor(Math.random() * subjects.length)];
    let thirdWord = verbs[Math.floor(Math.random() * verbs.length)];
    let fourthWord = objects[Math.floor(Math.random() * objects.length)];
    let fullSentence = ` ${firstWord} ${thirdWord} ${fourthWord}.`;
    return fullSentence;
  } else if (adverbsOnorOff >= 5 && adverbsOnorOff < 10) {
    let firstWord = beVerbs[Math.floor(Math.random() * beVerbs.length)];
    let secondWord = nextWord[Math.floor(Math.random() * nextWord.length)];
    let thirdWord = nextVerb[Math.floor(Math.random() * nextVerb.length)];
    let fourthWord = nextObject[Math.floor(Math.random() * nextObject.length)];
    let fifthWord = prepPhrase[Math.floor(Math.random() * prepPhrase.length)];
    let fullSentence = ` ${firstWord} ${secondWord} ${thirdWord} ${fourthWord} ${fifthWord}.`;
    return fullSentence;
  } else if (adverbsOnorOff >= 10 && adverbsOnorOff < 13) {
    let firstWord = modalVerbs[Math.floor(Math.random() * modalVerbs.length)];
    let secondWord = subjects[Math.floor(Math.random() * subjects.length)];
    let thirdWord = verbsiii[Math.floor(Math.random() * verbsiii.length)];
    let fourthWord = objects[Math.floor(Math.random() * objects.length)];
    let fullSentence = ` ${firstWord} ${secondWord.toLowerCase()} ${thirdWord} ${fourthWord}?`;
    return fullSentence;
  } else if (adverbsOnorOff >= 13 && adverbsOnorOff < 15) {
    let firstWord = modalVerbs[Math.floor(Math.random() * modalVerbs.length)];
    let secondWord = subjects[Math.floor(Math.random() * subjects.length)];
    let thirdWord = verbsiii[Math.floor(Math.random() * verbsiii.length)];
    let fourthWord = objects[Math.floor(Math.random() * objects.length)];
    let fifthWord = prepPhrase[Math.floor(Math.random() * prepPhrase.length)];
    let fullSentence = ` ${firstWord} ${secondWord.toLowerCase()} ${thirdWord} ${fourthWord} ${fifthWord}?`;
    return fullSentence;
  } else if (adverbsOnorOff >= 15 && adverbsOnorOff < 16) {
    let firstWord = questions[Math.floor(Math.random() * questions.length)];
    let thirdWord = adjectives[Math.floor(Math.random() * adjectives.length)];
    let fourthWord = objectsii[Math.floor(Math.random() * objectsii.length)];
    let fullSentence = ` ${firstWord} ${thirdWord} ${fourthWord}?`;
    return fullSentence;
  } else if (adverbsOnorOff >= 16 && adverbsOnorOff < 19) {
    let firstWord = questionBeVerbs[Math.floor(Math.random() * questionBeVerbs.length)];
    let thirdWord = posessives[Math.floor(Math.random() * posessives.length)];
    let fourthWord = objectsii[Math.floor(Math.random() * objectsii.length)];
    let fifthWord = nextVerb[Math.floor(Math.random() * nextVerb.length)];
    let sixthWord = adjectives[Math.floor(Math.random() * adjectives.length)];
    let seventhWord = objectsii[Math.floor(Math.random() * objectsii.length)];
    let fullSentence = ` ${firstWord} ${thirdWord} ${fourthWord} ${fifthWord} ${sixthWord} ${seventhWord}?`;
    return fullSentence;
  } else if (adverbsOnorOff >= 19 && adverbsOnorOff < 22) {
    let firstWord = blah[Math.floor(Math.random() * blah.length)];
    let secondWord = kakobunshi[Math.floor(Math.random() * kakobunshi.length)];
    let thirdWord = adjectives[Math.floor(Math.random() * adjectives.length)];
    let fourthWord = objectsii[Math.floor(Math.random() * objectsii.length)];
    let fifthWord = prepPhrase[Math.floor(Math.random() * prepPhrase.length)];
    let fullSentence = ` ${firstWord} ${secondWord} ${thirdWord} ${fourthWord} ${fifthWord}.`;
    return fullSentence;
  } else if (adverbsOnorOff >= 22 && adverbsOnorOff < 24) {
    let firstWord = 'Have you ever';
    let secondWord = kakobunshi[Math.floor(Math.random() * kakobunshi.length)];
    let thirdWord = adjectives[Math.floor(Math.random() * adjectives.length)];
    let fourthWord = objectsii[Math.floor(Math.random() * objectsii.length)];
    let fifthWord = prepPhrase[Math.floor(Math.random() * prepPhrase.length)];
    let fullSentence = ` ${firstWord} ${secondWord} ${thirdWord} ${fourthWord} ${fifthWord}?`;
    return fullSentence;
  } else {
    let firstWord = questionWords[Math.floor(Math.random() * questionWords.length)];
    let secondWord = nextWord[Math.floor(Math.random() * nextWord.length)];
    let thirdWord = nextVerb[Math.floor(Math.random() * nextVerb.length)];
    let fourthWord = nextObject[Math.floor(Math.random() * nextObject.length)];
    let fifthWord = prepPhrase[Math.floor(Math.random() * prepPhrase.length)];
    let fullSentence = ` ${firstWord} ${thirdWord} ${fourthWord} ${fifthWord}?`;
    return fullSentence;
  }
};

const subjects = [
  'You',
  'I',
  'You',
  'I',
  'Airlines',
  'Prospectors',
  'Detectives',
  'Biographers',
  'Lovers',
  'Lizards',
  'Tulips',
  'Grandmothers',
  'Messengers',
  'Fictional characters',
  'Boys',
  'Girls',
  'Drivers',
  'Magicians',
  'Carpet samples',
  'Groups of people',
  'Agents',
  'Monks',
  'Insects',
  'Hermits',
  'Your parents',
  'Mystics',
  'Journalists',
  'Hypocrites',
  'Young people',
  'Old people',
  'Illustrations',
  'Trolls',
  'Rats',
  'Doctors',
  'Engineers',
  'Farmers',
  'Barbers',
  'Arsonists',
  'Workers',
  'Visionaries',
  'Units',
  'Pants',
  'Factions',
  'Sailors',
  'Engineers',
  'Pilots',
  'Musicians',
  'Corners',
  'Angels',
  'Hippos',
  'Painters',
  'Mechanics',
  'Shadows',
  'Percentages',
  'Statistics',
  'Eggs',
  'Descriptions',
  'Columnists',
  'Journalists',
  'Flies',
  'Drugs',
  'Dolls',
  'Horses',
  'Witches',
  'Workers',
  'Drivers',
  'Mice',
  'Drug addicts',
  'Soloists',
  'Documents',
  'Alcoholics',
  'Public servants',
  'Thinkers',
  'Government employees',
  'Motherfuckers',
  'Intellectuals',
  'Historians',
  'Earthquakes',
  'Dinosaurs',
  'Psychics',
  'Raisins',
  'Revisionists',
  'Crustaceans',
  'Friends',
  'Doctors',
  'Lawyers',
  'Beans',
  'Pandas',
  'Our pets',
  'Revisionists',
  'Our fathers',
  'Our elders',
  'Knives',
  'Sandwiches',
  'Data',
  'Cults',
  'Chemists',
  'Bacteria',
  'Equations',
  'Heroes',
  'Flowers',
  'Capricorns',
  'Stars',
  'Sounds',
  'Opposing sides',
  'Triangles',
  'Wives',
  'Husbands',
  'Legends',
  'Qualities',
  'Disappoinments',
  'Peasants',
  'Lies',
  'Angels',
  'Arguments',
  'Farms',
  'Fires',
  'Brides',
  'Prisoners',
  'Alternate realities',
  'Universal truths',
  'Questions',
  'Senses',
  'Relationships',
  'Visions',
  'Boots',
  'Fools',
  'Philosophers',
  'Ambulances',
  'Gods',
  'Trolls',
  'Monks',
  'Mystics',
  'Clouds',
  'Apes',
  'Rain drops',
  'Crystals',
  'Sheep',
  'Diamonds',
  'Brains',
  'Hearts',
  'Feathers',
  'Butterflies',
  'Bodies',
  'Souls',
  'Gentlemen',
  'Prejudices',
  'Options',
  'Requirements',
  'Morals',
  'Ethics',
  'Identifiers',
  'Beliefs',
  'Concerns',
  'Kitchens',
  'Facts',
  'Opinions',
  'Corporations',
  'Anchors',
  'Designers',
  'Builders',
  'Functions',
  'Algorithms',
  'Babies',
  'Germs',
  'Juices',
  'Musicians',
  'Magicians',
  'Fevers',
  'Dreams',
  'Nurses',
  'Disappointments',
  'Detectives',
  'Bigots',
  'Bastards',
  'Flames',
  'Fabrications',
  'Realizations',
  'Camels',
  'Barns',
  'Fires',
  'Breeders',
  'Golfers',
  'Prophets',
  'Windows',
  'Afternoons',
  'Epiphanies',
  'Habits',
  'Habitats',
  'Climates',
  'Villans',
  'Kings',
  'Queens',
  'Beggars',
  'Fashions',
  'You',
  'Dogs',
  'We',
  'They',
  'Cows',
  'Wolves',
  'Cars',
  'Skateboards',
  'Ghosts',
  'Runners',
  'Politicians',
  'Sailors',
  'Killers',
  'Bananas',
  'Telephones',
  'Schools',
  'Monsters',
  'Poems',
  'Fish',
  'Rabbits',
  'Martians',
  'Concepts',
  'Intuitions',
  'Generations',
  'Scientists',
  'Rainbows',
  'Men',
  'Boys',
  'Girls',
  'Women',
  'Humans',
  'Zealots',
  'Bears',
  'Socks',
  'People',
  'Hermits',
  'Teachers',
  'Computers',
  'Televisions',
  'Poets',
  'Writers',
  'Vampires',
  'Priests',
  'Books',
  'Falcons',
  'Dictionaries',
  'Martyrs',
  'Markets',
  'Institutions',
  'Tumors',
  'Edges',
  'Facts',
  'Opinions',
  'Timelines',
  'Miracles',
  'Pilots',
  'Patriots',
  'Traitors',
  'Salesmen',
  'Physicists',
  'Engines',
  'Dice',
  'Marxists',
  'Crows',
  'Soldiers',
  'Humanists',
  'Educators',
  'Notes',
  'Receipts'
];
const adverbs = [
  'slowly',
  'tirelessly',
  'accidentally',
  'crassly',
  'openly',
  'nervously',
  ', too young to know any better, ',
  'briefly',
  ', without any clothes on, ',
  'slickly',
  'elegantly',
  'deceptively',
  'purposefully',
  'truthfully',
  '100% of the time',
  'temporarily',
  'hardly',
  'debatably',
  'rapidly',
  'patiently',
  'gleefully',
  'openly',
  'frankly',
  'with heavy hearts',
  'without delay',
  'frequently',
  'often',
  'likely',
  'solemnly',
  'ceremoniously',
  'annually',
  'hungrily',
  'sometimes',
  'once in a while',
  'at times',
  'every now and then',
  'always',
  'never',
  'metaphorically',
  'violently',
  'realistically',
  'respectfully',
  'actually',
  'reasonably',
  'habitually',
  'selfishly',
  'daily',
  'absentmindedly',
  'haphazardly',
  'quickly',
  'longingly',
  'silently',
  'pensively',
  'thoughtfully',
  'sadly',
  'happily',
  'joyfully',
  'intuitively',
  'absently',
  'nakedly',
  'refreshingly',
  'tiredly',
  'viciously',
  'beautifully',
  'regretably',
  'whimsically',
  'softly',
  'youthfully',
  'mournfully',
  'dejectedly',
  'intuitively',
  'handsomely',
  'lazily',
  'arrogantly',
  'overtly',
  'reasonably',
  'telepathically',
  'generously'
];
const verbs = [
  'come across',
  'falsify',
  'design',
  'search for',
  'explore',
  'dissect',
  'investigate',
  'take pictures of',
  'disappoint',
  'let down',
  'judge',
  'sponsor',
  'forgive',
  'chant about',
  'arrest',
  'absorb',
  'look like',
  'listen to',
  'hang',
  'squeeze',
  'satisfy',
  'expose their',
  'brag about',
  'lend a helpinng hand to',
  'support',
  'worship',
  'worry about',
  'give advice to',
  'experience',
  'measure',
  'cure',
  'stabilize',
  'fix',
  'spill',
  'ban',
  'sleep with',
  'hang on to',
  'enjoy',
  'request',
  'tie up',
  'pee',
  'scratch',
  'harrass',
  'investigate',
  'trip',
  'shame',
  'fetishize',
  'reduce the number of',
  'banish',
  'chase',
  'sacrifice',
  'stalk',
  'manipulate',
  'disrupt',
  'shave',
  'grill',
  'exhaust',
  'spoil',
  'harm',
  'exhume',
  'excavate',
  'deconstruct',
  'reconstruct',
  'film',
  'pacify',
  'unite',
  'discover',
  'put on',
  'wear',
  'show off their',
  'grill',
  'describe in detail their',
  'are supporters of',
  'taste',
  'scream about',
  'drink',
  'scratch',
  'point at',
  'do not understand',
  'walk past',
  'ignore',
  'drink',
  'get intoxicated on',
  'do not want',
  'are not',
  'harbor feelings of hatred for',
  'forget',
  'enslave',
  'colonize',
  'make movies about',
  'direct',
  'stare at',
  'incinerate',
  'cremate',
  'concentrate on',
  'hallucinate about',
  'raise questions about the virtues of',
  'massage',
  'signify',
  'make an exception for',
  'refuse to accept',
  'discharge',
  'melt',
  'boast about',
  'praise',
  'assemble',
  'track',
  'tell lies about',
  'make up stories about',
  'make a toast to',
  'assasinate',
  'drink',
  'romanticize',
  'bring law suits against',
  'cure',
  'renew their subscription to',
  'pardon',
  'verify the authenticity of',
  'put poison in',
  'bless',
  'inspect',
  'reflect on',
  'carry on about',
  'reconfigure',
  'collide into',
  'dismiss',
  'smoke',
  'critique',
  'refuse to participate in',
  'fart on',
  'hide',
  'reveal their',
  'cannot recall',
  'distrust',
  'transform',
  'call into question the nature of',
  'criticise the rationale for',
  'call for an end to',
  'entrust their lives to',
  'draw conclusions about',
  'dispose of',
  'cough up',
  'denounce',
  'secrete',
  'respect',
  'banish',
  'reward',
  'cancel',
  'rename',
  'overthrow',
  'make offerings to',
  'legitamize',
  'persuade',
  'collide with',
  'vilify',
  'forsake',
  'betray',
  'analyze',
  'demystify',
  'recycle',
  'impregnate',
  'vomit up',
  'bleed',
  'express their hatred of',
  'question the validity of',
  'collect',
  'annoint',
  'give lectures on',
  'offer prayers for',
  'are disappointed in',
  'are imbricated and embedded within the texture of',
  'disappoint',
  'are becoming',
  'are not',
  'are curious about',
  'are happy with',
  'are satisfied with',
  'are near',
  'are seen under',
  'are disappointed in',
  'are devouring',
  'lust after',
  'feature in',
  'die in',
  'beatify',
  'clean',
  'wash',
  'sniff',
  'get excited about',
  'stab',
  'impale themselves upon',
  'smell of',
  'drip',
  'leak',
  'execute',
  'lie down with',
  'inhabit',
  'prioritize',
  'sing of',
  'detune',
  'blow up',
  'hate',
  'get exercise with',
  'admit',
  'turn away',
  'recognize',
  'paraphrase',
  'read the thoughts of',
  'acquire',
  'require',
  'conceive',
  'kick',
  'sleep beneath',
  'walk on',
  'push',
  'swing',
  'falsify',
  'deny',
  'fight over',
  'make',
  'resemble',
  'hurt',
  'falsify',
  'hold back',
  'restrain',
  'detain',
  'debate the existence of',
  'describe',
  'have success with',
  'wish for',
  'define',
  'recreate',
  'oppress',
  'suppress',
  'get revenge on',
  'long for',
  'thirst for',
  'sympathize with',
  'identify with',
  'hold on to',
  'start rumors about',
  'insult',
  'put down',
  'give way to',
  'get off on',
  'get it on with',
  'teleport',
  'carry off',
  'itemize',
  'look down on',
  'get in',
  'tolerate',
  'violate',
  'cut out',
  'leave without',
  'hang on to',
  'blow on',
  'eat',
  'sing about',
  'call',
  'bury',
  'find',
  'search for',
  'elope with',
  'liquify',
  'terrify',
  'cook',
  'burn',
  'improvise',
  'underline',
  'become',
  'regret',
  'define',
  'evaluate',
  'bite',
  'harmonize',
  'renew',
  'conceptualize',
  'sit on',
  'jump over',
  'run up and down',
  'bake',
  'destroy',
  'reward',
  'relate to',
  'generate',
  'falsify',
  'patronize',
  'repulse',
  'repent for',
  'pray for',
  'install',
  'revise',
  'turn over',
  'think about',
  'cringe when thinking about',
  'nullify',
  'inject',
  'smoke',
  'relate to',
  'objectify',
  'retaliate against',
  'beautify',
  'apologize on behalf of',
  'respond to criticisms of',
  'daydream of',
  'engage',
  'reject',
  'verify',
  'quantify',
  'grind',
  'regulate',
  'standardize',
  'persuade',
  'fax',
  'write about',
  'dwell in',
  'reassure',
  'scratch',
  'create',
  'mistrust',
  'moderate',
  'gnaw on',
  'weigh',
  'draw',
  'calculate',
  'dismiss',
  'synthesize',
  'resurrect',
  'reconstruct',
  'debate the merits of',
  'edify',
  'delight',
  'inflate'
];
const objects = [
  'politics',
  'mercy',
  'manuscripts',
  'equipment',
  'knowledge',
  'metaphors',
  'mittens',
  'metal',
  'pride',
  'ignorance',
  'raisins',
  'ice',
  'possessions',
  'consciousness',
  'bones',
  'logos',
  'cassette tapes',
  'sweaters',
  'riddles',
  'rhymes',
  'bar codes',
  'sound',
  'bridges',
  'infinity',
  'lungs',
  'materials',
  'olives',
  'drums',
  'trains',
  'music',
  'bread',
  'finger nails',
  'poverty',
  'wealth',
  'insomnia',
  'ponies',
  'documents',
  'documentaries',
  'viruses',
  'wounds',
  'illustrations',
  'scars',
  'plastic',
  'skateboarders',
  'pants',
  'movies',
  'knives',
  'chess champions',
  'wigs',
  'nuts',
  'hearts',
  'candles',
  'kittens',
  'shame',
  'industries',
  'wheels',
  'shadows',
  'fingers',
  'destruction',
  'insects',
  'teeth',
  'freedom',
  'leopards',
  'crumbs',
  'buckets',
  'breasts',
  'falsehoods',
  'rumors',
  'birth',
  'minds',
  'death',
  'blood',
  'gas',
  'famine',
  'hunger',
  'telegrams',
  'hair',
  'creation',
  'destruction',
  'innovations',
  'signs',
  'symbols',
  'numbers',
  'hypocrisy',
  'processes',
  'the universe',
  'principles',
  'tragedies',
  'bicycles',
  'leather',
  'shoe polish',
  'bird beaks',
  'skin',
  'scabs',
  'warts',
  'everyone',
  'parrots',
  'bamboo',
  'kindness',
  'corpses',
  'their mothers',
  'their fathers',
  'galaxies',
  'solitude',
  'oil',
  'goats',
  'dirt',
  'stones',
  'bricks',
  'geometry',
  'mud',
  'fantasies',
  'rubbish',
  'grease',
  'underpants',
  'street lamps',
  'Christmas',
  'amphibians',
  'snakes',
  'semantics',
  'priorities',
  'sisters',
  'regret',
  'emergency vehicles',
  'blankets',
  'deception',
  'colors',
  'their brothers',
  'rainbows',
  'rooves',
  'creatures',
  'success',
  'pineapples',
  'beards',
  'food',
  'fatalities',
  'hatred',
  'diseases',
  'voters',
  'harmony',
  'peace',
  'violence',
  'nothing',
  'nobody',
  'each and every one of us',
  'humanity',
  'logic',
  'fate',
  'frames',
  'coins',
  'history',
  'definitions',
  'radios',
  'philosophy',
  'reason',
  'wizards',
  'the police',
  'bread',
  'electricity',
  'cheese',
  'milk',
  'sheep',
  'rice',
  'Rome',
  'Tokyo',
  'gold',
  'potatoes',
  'fluids',
  'juice',
  'silver',
  'spoons',
  'regret',
  'urine',
  'forks',
  'sickness',
  'fluids',
  'reality',
  'the moon',
  'comets',
  'gasoline',
  'rockets',
  'bile',
  'a carrot',
  'penguins',
  'management',
  'hospitals',
  'board meetings',
  'relationships',
  'apples',
  'oxygen',
  'hydrogen',
  'inanimate objects',
  'teeth',
  'beads',
  'seeds',
  'plants',
  'all living things',
  'animals',
  'Earth',
  'New York',
  'Paris',
  'Mexico',
  'Bolivia',
  'rewards',
  'golf',
  'numbers',
  'sin',
  'punishment',
  'the government',
  'designer jeans',
  'ghosts',
  'the distant past',
  'pragmatics',
  'unrealized dreams',
  'ancient history',
  'absurdity',
  'the future',
  'realism',
  'egoism',
  'romanticism',
  'my idealism',
  'individualism',
  'symbolism',
  'your husband',
  'your car',
  'metaphysics',
  'our town',
  'our houses',
  'my cat',
  'entropy',
  'unity',
  'glue',
  'intangible concepts',
  'household objects',
  'cablecars',
  'crows',
  'factories',
  'penguins',
  'us',
  'men',
  'Canadians',
  'concepts',
  'art',
  'abstractions',
  'realizations',
  'protons',
  'elephants',
  'trees',
  'wood',
  'forests',
  'harnesses',
  'bridges',
  'cities',
  'countries',
  'people',
  'idiots',
  'scales',
  'techniques',
  'religions',
  'mothers',
  'fathers',
  'parties',
  'fish',
  'you',
  'ideas',
  'memes',
  'qualities',
  'revisions',
  'desks',
  'late nights',
  'books',
  'heaven',
  'hell',
  'corporations',
  'bookshelves',
  'masterpieces',
  'bandits',
  'America',
  'Europe',
  'airplanes',
  'knives',
  'oceans',
  'donuts',
  'policies',
  'microscopes',
  'neighbors',
  'winds',
  'arrows',
  'laws',
  'criminals',
  'pyramids',
  'frogs',
  'sanity',
  'institutions'
];

const beVerbs = [
  'I am',
  'Everybody is',
  'Artists are',
  'Penguins are',
  'Kittens are',
  'A dragon is',
  'People are',
  'All of us are',
  'The prime minister is',
  'Professors are',
  'Henry Rollins is',
  'Our mothers are',
  'Our fathers are',
  'The sun is',
  'The moon is',
  'My bicycle is',
  'That thing over there is',
  'Liberal democracies are',
  'Nobody is',
  'Somebody is',
  'Creatures are',
  'My thoughts are',
  'Your closest friends are',
  'Our sadness is',
  'Our pain is',
  'Your thoughts are',
  'He is',
  'Farmers are',
  'The rainbow is',
  'My sense of self-worth is',
  'She is',
  'We are',
  'My aunt is',
  'My finger is',
  'Your cousin is',
  'Your mother is',
  'I am',
  'Vampires are',
  'Birds are',
  'Liars are',
  'His face is',
  'Their students are',
  'The chosen one is',
  'Your teacher is',
  'Your pets are',
  'Their ancestors are',
  'Your teeth are',
  'My lunch is',
  'Their instructors are',
  'Our brains are',
  'Trees are',
  'The milkman is',
  'Your boyfriend is',
  'My eyes are',
  'Prophets are',
  'Your favorite musician is',
  'Your hobby is',
  'My hobby is',
  'Your house is',
  'Revisionists are',
  'Your dentist is',
  'Your cat is',
  'Your dog is',
  'Our pets are',
  'My fish is',
  'His boss is',
  'Our king is',
  'Giants are',
  'The president is',
  'Her best friend is',
  'Your aunt is',
  'Their elephant',
  'My parole officer is',
  'Our friends are',
  'Your family is',
  'Your father is',
  'They are',
  'Rabbits are',
  'Students are',
  'Dinosaurs are',
  'Traitors are',
  'Enemies are',
  'My uncle is',
  'Thinking is',
  'Friends are',
  'Fantasies are',
  'Families are',
  'Society is',
  'Mathematics is',
  'Officials are',
  'Ideas are',
  'Mothers are',
  'Fathers are',
  'Grandmothers are',
  'Grandfathers are',
  'Militaries are',
  'Idiots are',
  'Politicians are',
  'My life is',
  'Our relationship is'
];
const nextWord = [
  'not',
  'already',
  '',
  '',
  '',
  'forever',
  'now',
  'silently',
  'tirelessly',
  'basically',
  'actually',
  'always',
  'again',
  'perhaps',
  'emotionally',
  'bravely',
  'aggresively',
  'eagerly',
  'hesitantly',
  'possibly',
  'frequently',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'thorougly',
  'busy',
  'sometimes',
  'unable to be',
  'not always',
  'without a doubt',
  'pensively',
  'probably',
  'unquestionably',
  'never',
  'without fail',
  'soon'
];
const nextVerb = [
  'thinking about',
  'riding',
  'scratching',
  'buying',
  'commanding',
  'concentrating on',
  'paying attention to',
  'thanking',
  'forgiving',
  'photographing',
  'absorbing',
  'dancing with',
  'exposing',
  'researching',
  'bragging about',
  'shaving',
  'peeling off',
  'boasting about',
  'worshiping',
  'spilling',
  'traveling with',
  'retaliating against',
  'observing',
  'fixing',
  'romanticising',
  'rehabilitating',
  'eating',
  'dining with',
  'hitting',
  'in love with',
  'in sink with',
  'fond of',
  'knowledeable about',
  'sleeping with',
  'listening to',
  'illustrating',
  'publishing',
  'projecting',
  'wishing death upon',
  'listing',
  'scratching',
  'stealing',
  'enjoying',
  'dancing upon',
  'chasing',
  'rescuing',
  'writing on',
  'assisting',
  'decorating',
  'giving presents to',
  'giving presentations on',
  'peeing on',
  'arguing about',
  'ashamed of',
  'torturing',
  'blaming their problems on',
  'licking',
  'adjusting',
  'feeling',
  'stepping on',
  'wishing for',
  'demanding',
  'disrupting',
  'asking questions about',
  'getting married with',
  'getting drunk with',
  'sacrificing',
  'manipulating',
  'crafting',
  'kissing',
  'hugging',
  'judging',
  'practicing',
  'investigating',
  'painting portraits of',
  'cleaning the insides of',
  'singing songs about',
  'breaking',
  'satirizing',
  'leaking',
  'studying',
  'preaching about',
  'hoping for',
  'recommending',
  'verifying',
  'replacing the vital parts of',
  'explaining',
  'restructuring',
  'polishing',
  'calling',
  'ruining',
  'giving a massage to',
  'disassembling',
  'melting',
  'seething with',
  'having a conversation with',
  'asking favors of',
  'assembling',
  'making love to',
  'contemplating',
  'pandering to',
  'yelling at',
  'questioning',
  'disciplining',
  'scolding',
  'throwing rocks at',
  'punishing',
  'rewarding',
  'discussing',
  'enslaving',
  'drawing conclusions about',
  'kind to',
  'stealing',
  'writing letters to',
  'playing with',
  'drawing pictures of',
  'crushing',
  'smashing',
  'shattering',
  'freezing',
  'ignoring',
  'fussing over',
  'illustrating',
  'feeling',
  'hugging',
  'manufacturing',
  'wishing the worst for',
  'wondering about',
  'discharging',
  'sitting on',
  'kicking',
  'repeating lies about',
  'spreading rumours about',
  'ruining the reputation of',
  'bleeding',
  'crying tears of',
  'farting on',
  'kissing',
  'defaming',
  'denying the existence of',
  'refusing to even consider',
  'writing about',
  'calling into question the validity of',
  'debating the merits of',
  'discussing',
  'talking about',
  'lusting after',
  'perplexed by',
  'destoryed by',
  'hurt by',
  'burned by',
  'interested in',
  'killing',
  'cleaning',
  'rubbing',
  'cursing',
  'smoking',
  'burning',
  'fermenting',
  'disillusioned by',
  'hungry for',
  'making'
];
const nextObject = [
  'hunger',
  'crystals',
  'computer graphics',
  'the past',
  'crabs',
  'socks',
  'guitars',
  'laws',
  'rocks',
  'spaceships',
  'executions',
  'shopping bags',
  'ignorance',
  'possessions',
  'penguins',
  'lettuce',
  'spinach',
  'magazines',
  'tables',
  'veiled accusations',
  'bread',
  'houses',
  'chairs',
  'emotions',
  'pillows',
  'decay',
  'kindness',
  'tables',
  'trees',
  'amnesia',
  'recipes',
  'clouds',
  'sand',
  'requests',
  'black holes',
  'cereal',
  'fingers',
  'toes',
  'bricks',
  'the earth',
  'humanity',
  'toads',
  'misery',
  'turtles',
  'destruction',
  'sadness',
  'destruction',
  'steel',
  'murder',
  'exams',
  'bread',
  'rice',
  'beer',
  'religion',
  'reality',
  'truth',
  'emotions',
  'kings',
  'queens',
  'peasants',
  'patrons',
  'artists',
  'alcohol',
  'explosions',
  'pollution',
  'consequences',
  'hatred',
  'medicine',
  'popcorn',
  'your face',
  'your sense of dignity',
  'writers',
  'butter',
  'poets',
  'liquids',
  'girls',
  'boys',
  'reporters',
  'wine',
  'cheese',
  'clouds',
  'sea creatures',
  'bears',
  'car crashes',
  'science',
  'clowns',
  'dinosaurs',
  'prisoners',
  'computers',
  'ideas',
  'thoughts',
  'creation',
  'guns',
  'bombs',
  'toilets',
  'cars',
  'balloons',
  'guts',
  'junk',
  'researchers',
  'evil',
  'fire',
  'flowers',
  'pigs',
  'candy',
  'fire',
  'air',
  'underpants',
  'sharp objects',
  'cars',
  'toys',
  'objects',
  'people',
  'gorillas',
  'mice',
  'princes',
  'pumpkins',
  'calculations',
  'drugs',
  'diseases',
  'facts',
  'stones',
  'balls',
  'cigarrettes'
];
const prepPhrase = [
  'alone',
  'on weekends',
  'without a second thought',
  'back here',
  'ad nauseam',
  'on sunny days',
  'on your chest',
  'under the bridge',
  'under a table',
  'on Halloween',
  'under the sea',
  'on top of a hill',
  'in your pocket',
  'in my mind',
  'in the hallway',
  'in the hospital',
  'in the graveyard',
  'in a hotel room',
  'in the refrigerator',
  'in the snow',
  `at my grandmother's house`,
  'outside',
  'indoors',
  'in the valley',
  'in the trees',
  'on bicycles',
  'at the station',
  'at the bus stop',
  'on a secluded island',
  'in the mountains',
  'with me',
  'in the grass',
  'in the bushes',
  'in the dirt',
  'in oil',
  'on Jupiter',
  'in traffic',
  'in the library',
  'when nobody is looking',
  'on the internet',
  'on the carpet',
  'on the wall',
  'in the woods',
  'no matter what',
  'alone before God',
  'before breakfast',
  'in the chapel',
  'on another planet',
  'at the supermarket',
  'in a convenience store',
  'behind your back',
  'in a hole',
  'on the way to school',
  'at a restaurant',
  'overseas',
  'for no reason at all',
  'for a laugh',
  'in the air',
  'on land',
  'on a boat',
  'by mistake',
  'in Rome',
  'in your ear',
  'on top of a mountain',
  'in Paris',
  'while drinking heavily',
  'with one hand',
  'on the other side of town',
  'on the roof',
  'while reading',
  'on the roadside',
  'while driving',
  'while wearing headphones',
  'while playing basketball',
  'while doing homework',
  'under the sink',
  'in the toilet',
  'in reality',
  'without laughing',
  'without permission',
  'under the moon',
  'in a row',
  'in flames',
  'at noon',
  'at the movies',
  'at the kitchen table',
  'after much consideration',
  'while smoking',
  'in our dreams',
  'while walking',
  'without knowing why',
  'by the river',
  'where everyone can see',
  'on the stage',
  'in the sand',
  'while talking',
  'while eating',
  'while exercising',
  'out of curiosity',
  'by coincidence',
  "with nobody's blessings ",
  'on the road',
  'under oath',
  'out of fear',
  'in disguise',
  'in solitude',
  'by the side of the road',
  'on a regular basis',
  'on an expedition',
  'on behalf of us',
  'by design',
  'by force',
  'out of kindess',
  'out of respect for your grandmother',
  'in high spirits',
  'at your request',
  'without your approval',
  'at your expense',
  'in the grass',
  'across the street',
  'at the speed of light',
  'at the park',
  'at their leisure',
  'at length',
  'at a standstill',
  'at all costs',
  'at lunch time',
  'while we weep',
  'for everyone to see',
  'in secret',
  'in my shoes',
  'in your desk',
  'on the ground',
  'with your sister',
  'with your cat',
  'with your dog',
  'behind the counter',
  'in a distant land',
  'in a distant galaxy',
  'in a tuxedo',
  'in space',
  'amongst the stars',
  'under your hat',
  'under my pillow',
  'behind your back',
  'in front of your parents',
  'first thing in the morning',
  'while walking',
  'instead of studying',
  'instead of working',
  'at the altar',
  'in public',
  'at night',
  'at the office',
  'in hiding',
  'in your pants',
  'by the window',
  'while we are sleeping',
  'on the floor',
  'in the summer',
  'while we dance',
  'when it rains',
  'in the closet',
  'in the car',
  'in bed',
  'on Thurdays',
  'on the train',
  'in the shadows',
  'with abandon',
  'in the snow',
  'on the veranda',
  'after dinner',
  'in orbit around the sun',
  'while crying',
  'in boxes',
  'on the beach',
  'underground',
  'on cold days',
  'at my funeral',
  'in January',
  'at midnight',
  'washing dishes',
  'while cooking',
  'while sleeping',
  'while swimming',
  'under the water',
  'in the garbage can',
  'in the sink',
  'behind the curtains',
  'at the supermarket',
  'when drunk',
  'at sea',
  'at parties',
  'with hair',
  'with eyes',
  'at home',
  'while you watch TV',
  'at work',
  'in my heart',
  'in cities',
  'beyond the horizon',
  'on the other side',
  'with wings',
  'on the streets',
  'at war',
  'eating food',
  'singing songs',
  'listening to music',
  'after work',
  'under the bed',
  'in the trees',
  'during meetings',
  'while reading',
  'while riding bicycles',
  'in the toilet',
  'behind the wall',
  'between the sheets',
  'in the sky',
  'on the moon',
  'at church',
  'in the attic',
  'at school',
  'in front of everybody',
  'in front of police officers',
  'above the clouds',
  'above the ground',
  'here on earth',
  'of other people',
  'at times'
];
const questionWords = [
  'Who is',
  'What is',
  'Who are',
  'Why are you',
  'Why am I',
  'Why are they',
  'Why are we',
  "Who isn't",
  'Are you going to be',
  'Are they going to be',
  'Am I going to be',
  'Are we going to be',
  'Why is your sister',
  "Why aren't you",
  'Why is my neighbor',
  'Why is your brother',
  'Why is your grandmother',
  'Why is your cousin',
  'Why is the pig',
  'Why are our parents',
  'What is',
  'Why are the animals',
  "Who isn't",
  'Why is that thing over there',
  'What is',
  'Why are the ducks',
  'Why is everyone',
  'Why is nobody',
  "Why aren't you",
  'Who is',
  'Why am I',
  'Why is the car',
  'Why is the dinosaur',
  'Why is the toilet',
  'Why are you',
  'Who is',
  'Why are they',
  'What is',
  'How come you are',
  'How come I am',
  'Why is my cat',
  'Why is your dog',
  'Why are our pets',
  'Why are their thoughts',
  'Why are they always',
  'Why is my fish',
  'Why is your friend',
  'Why are you',
  'Why are we'
];

const verbsiii = [
  'come across',
  'fetishize',
  'disrupt',
  'honor',
  'betray',
  'discover',
  'put on their',
  'wear',
  'entertain',
  'show off their',
  'grill',
  'describe in detail their',
  'laugh about',
  'taste',
  'invent',
  'scream about',
  'drink',
  'scratch',
  'point at',
  'hug',
  'walk past',
  'anticipate',
  'pee',
  'ignore',
  'drink',
  'get intoxicated on',
  'whip',
  'put up with',
  'harbor feelings of hatred for',
  'forget',
  'enslave',
  'colonize',
  'make movies about',
  'direct',
  'stare at',
  'incinerate',
  'cremate',
  'concentrate on',
  'hallucinate about',
  'raise questions about the virtues of',
  'massage',
  'signify',
  'make an exception for',
  'refuse to accept',
  'discharge',
  'make a toast to',
  'assasinate',
  'drink',
  'romanticize',
  'bring law suits against',
  'cure',
  'renew their subscription to',
  'pay tribute to',
  'pardon',
  'verify the authenticity of',
  'put poison in',
  'bless',
  'reconfigure',
  'dismiss',
  'smoke',
  'critique',
  'conspire to murder',
  'refuse to participate in',
  'fart on',
  'hide',
  'reveal their',
  'recycle',
  'distrust',
  'transform',
  'call into question the nature of',
  'criticise the rationale for',
  'call for an end to',
  'entrust their lives to',
  'draw conclusions about',
  'dispose of',
  'cough up',
  'denounce',
  'secrete',
  'respect',
  'banish',
  'reward',
  'cancel',
  'rename',
  'overthrow',
  'make offerings to',
  'legitamize',
  'persuade',
  'vilify',
  'forsake',
  'betray',
  'analyze',
  'demystify',
  'justify',
  'impregnate',
  'vomit up',
  'bleed',
  'express their hatred of',
  'question the validity of',
  'collect',
  'annoint',
  'give lectures on',
  'offer prayers for',
  'show disapproval of',
  'disappoint',
  'become',
  'become',
  'stomp on',
  'be happy with',
  'be satisfied with',
  'stay near',
  'be seen under',
  'be disappointed in',
  'lust after',
  'feature in',
  'die in',
  'sniff',
  'stab',
  'be impaled upon',
  'smell of',
  'drip',
  'leak',
  'execute',
  'lie down with',
  'inhabit',
  'prioritize',
  'sing of',
  'detune',
  'blow up',
  'hate',
  'get exercise with',
  'admit',
  'turn away',
  'recognize',
  'paraphrase',
  'read the thoughts of',
  'acquire',
  'require',
  'conceive',
  'kick',
  'sleep beneath',
  'walk on',
  'cleanse',
  'wash',
  'push',
  'swing',
  'falsify',
  'deny',
  'fight over',
  'make',
  'resemble',
  'hurt',
  'falsify',
  'hold back',
  'restrain',
  'detain',
  'debate the existence of',
  'whisper to',
  'describe',
  'have success with',
  'wish for',
  'define',
  'recreate',
  'oppress',
  'suppress',
  'get revenge on',
  'long for',
  'thirst for',
  'sympathize with',
  'identify with',
  'hold on to',
  'start rumors about',
  'insult',
  'put down',
  'give way to',
  'get off on',
  'get it on with',
  'teleport',
  'carry off',
  'itemize',
  'look down on',
  'get in',
  'tolerate',
  'violate',
  'cut out',
  'leave without',
  'hang on to',
  'blow on',
  'eat',
  'sing about',
  'call',
  'bury',
  'find',
  'search for',
  'elope with',
  'liquify',
  'terrify',
  'cook',
  'burn',
  'improvise',
  'underline',
  'become',
  'regret',
  'define',
  'evaluate',
  'bite',
  'harmonize',
  'renew',
  'conceptualize',
  'sit on',
  'jump over',
  'run up and down',
  'bake',
  'destroy',
  'reward',
  'relate to',
  'generate',
  'falsify',
  'patronize',
  'repulse',
  'repent for',
  'pray for',
  'install',
  'revise',
  'turn over',
  'think about',
  'cringe when thinking about',
  'nullify',
  'inject',
  'smoke',
  'relate to',
  'objectify',
  'retaliate against',
  'beautify',
  'apologize on behalf of',
  'daydream of',
  'engage',
  'reject',
  'verify',
  'quantify',
  'grind',
  'regulate',
  'standardize',
  'persuade',
  'fax',
  'write about',
  'dwell in',
  'reassure',
  'create',
  'mistrust',
  'moderate',
  'gnaw on',
  'weigh',
  'draw',
  'calculate',
  'dismiss',
  'synthesize',
  'reconstruct',
  'debate the merits of',
  'edify',
  'silence',
  'delight',
  'inflate'
];
const modalVerbs = [
  'Can',
  'Can',
  'Do',
  'Do',
  'Why do',
  'How do',
  'Should',
  'Will',
  'Must',
  'Why must',
  'When will',
  'How can',
  'How should',
  'Why do',
  "Why can't",
  "Why don't",
  'Can',
  'Do'
];

const questionBeVerbs = ['Is', 'Was'];
const posessives = ['my', 'your', 'our', 'his', 'her', 'their', 'our'];

const questions = [
  'Why are you',
  'Are you',
  'Am I',
  'Is he made out of',
  'Is she made out of',
  'Are we',
  'Are they',
  'Is everyone',
  'Is anyone',
  'Is this',
  'Is that'
];
const adjectives = [
  'a vague',
  'a three year old',
  'a pleasing',
  'a scholarly',
  'an elderly',
  'a childish',
  'a problematic',
  'an untouchable',
  'an unheard of',
  'a symbolic',
  'a three year old',
  'a witty',
  'a natural',
  'a sophisticated',
  'a purple',
  'a dubious',
  'a bearded',
  'a beardless',
  'a rusted',
  'a spoiled',
  'a fragmented',
  'an empty',
  'a nuclear',
  'a glowing',
  'a rubber',
  'a glossy',
  'an optional',
  'an infinite',
  'a glossy',
  'a certain',
  'beasts',
  'a silver',
  'a beautiful',
  'a graceful',
  'a specific',
  'a peculiar',
  'a musical',
  'a tiny',
  'a handsome',
  'a plump',
  'an obnoxious',
  'a blasphemous',
  'a hairy',
  'an educated',
  'an itchy',
  'a virtuous',
  'a skinny',
  'a diseased',
  'a faithful',
  'a hesitant',
  'a bashful',
  'an injured',
  'a filthy',
  'a lonely',
  'an undefined',
  'a numerical',
  'a circular',
  'a rectangular',
  'a filfthy',
  'a poisonous',
  'a bald',
  'a sarcastic',
  'an ironic',
  'an arctic',
  'a fresh',
  'a plastic',
  'a gentle',
  'a removable',
  'an uncontrollable',
  'a glass',
  'a flexible',
  'a green',
  'a blue',
  'a brown',
  'a black',
  'a white',
  'an industrial',
  'an innocent',
  'an unremarkable',
  'an unreasonable',
  'a pale',
  'a weeping',
  'a burning',
  'a smoking',
  'a blank',
  'a vomiting',
  'an unrealized',
  'an unrealistic',
  'a familiar',
  'a terrifying',
  'an unknown',
  'a reasonable',
  'a telepathic',
  'an unscientific',
  'a rectangular',
  'a solid',
  'a liquid',
  'an orange',
  'a red',
  'a strange',
  'a handsome',
  'a talkative',
  'a generous',
  'an arrogant',
  'a talking',
  'an innocent',
  'a young',
  'an old',
  'a reasonable',
  'a reusable',
  'a destructive',
  'a misspelled',
  'a disciplined',
  'a creative',
  'a blind',
  'a tired',
  'a sleepy',
  'an impossible',
  'a stupid',
  'a new',
  'a sick',
  'a foamy',
  'a smelly',
  'a stinky',
  'an understandable',
  'an understated',
  'an important',
  'an improvised',
  'an honorable',
  'a virtuous',
  'a programmable',
  'a naive',
  'a quiet',
  'a pleasant',
  'a fast',
  'an unoriginal',
  'a deep fried',
  'a useless',
  'a fake',
  'a coughing',
  'a pointless',
  'a tall',
  'a short',
  'a renewable',
  'a hateful',
  'a dark',
  'a dangerous',
  'a romantic',
  'a shameful',
  'a hideous',
  'a wicked',
  'a shriveled',
  'a dirty',
  'a tired',
  'a violent',
  'a blank',
  'a rancid',
  'a rotten',
  'a senile',
  'a late',
  'a recognizable',
  'a strong',
  'a cheerful',
  'a frozen',
  'a gaseous',
  'a non-existant',
  'a perfect',
  'an invisible',
  'an indestructable',
  'an imagined',
  'a flawless',
  'a cramped',
  'a small',
  'a big',
  'a terrible',
  'an unknown',
  'a lazy',
  'a proud',
  'an opinionated',
  'a flavorless',
  'a bland',
  'a tasty',
  'a crunchy',
  'a soft',
  'a silky',
  'a smooth',
  'a sharp',
  'a hard',
  'a pointed',
  'a difficult',
  'a dreamy',
  'a smokey',
  'a boring',
  'a loose',
  'a gold',
  'a happy',
  'a spicy',
  'a friendly',
  'a ficticious',
  'a real',
  'an endless',
  'an infinite',
  'a cold',
  'a hot',
  'a warm',
  'a rough',
  'a realistic',
  'an abstract',
  'a wax',
  'a bloody',
  'a restrained',
  'an unknowable',
  'a joyful',
  'a joyless',
  'a sensuous',
  'a luxurious',
  'a hesitant',
  'a nice',
  'a feminine',
  'a denim',
  'a masculine',
  'a fashionable',
  'a healthy',
  'an illustrated',
  'a sick'
];
const objectsii = [
  'idea',
  'goat',
  'prune',
  'glass of wine',
  'body',
  'bridge',
  'spiritual being',
  'fox',
  'knob',
  'method',
  'mechanism',
  'bone',
  'condition',
  'machine',
  'face',
  'self-contradiction',
  'TV',
  'screen',
  'sentence',
  'claw',
  'nose',
  'foot',
  'leg',
  'arm',
  'eye',
  'mouth',
  'tongue',
  'pilgrim',
  'puppy',
  'neck',
  'ear',
  'drum',
  'nail',
  'key',
  'finger nail',
  'sense of humor',
  'rope',
  'sum of money',
  'number',
  'project',
  'faucet',
  'sailor',
  'bear',
  'shirt',
  'shark',
  'sin',
  'virus',
  'chicken',
  'host',
  'scar',
  'kitten',
  'finger',
  'drain pipe',
  'decoy',
  'brain',
  'shadow',
  'fist',
  'leopard',
  'crumb',
  'bucket',
  'sense of shame',
  'piece of garbage',
  'goggle',
  'revolution',
  'breast',
  'falsehood',
  'rumor',
  'baby',
  'mind',
  'death',
  'pool of blood',
  'gas',
  'famine',
  'feeling of hunger',
  'telegram',
  'strand of hair',
  'creation',
  'destructive force',
  'innovation',
  'sign',
  'symbol',
  'number',
  'hypocrit',
  'process',
  'universe',
  'principle',
  'tragedy',
  'bicycle',
  'piece of leather',
  'can of shoe polish',
  'bird beak',
  'flake of skin',
  'scab',
  'wart',
  'ear',
  'parrot',
  'bamboo tree',
  'nose',
  'sense of kindness',
  'corpse',
  'mother',
  'father',
  'galaxy',
  'feeling of solitude',
  'oil',
  'goat',
  'piece of dirt',
  'stone',
  'brick',
  'form of geometry',
  'puddle of mud',
  'fantasy',
  'pile of rubbish',
  'prank',
  'pie',
  'grease gun',
  'pair of pants',
  'street lamp',
  'Christmas tree',
  'amphibian',
  'snake',
  'misrepresentation',
  'priority',
  'sister',
  'regret',
  'emergency vehicle',
  'blanket',
  'flag',
  'falsehood',
  'color',
  'blanket',
  'ape',
  'deception',
  'color',
  'brother',
  'rainbow',
  'creature',
  'feeling of success',
  'pineapple',
  'beard',
  'piece of food',
  'fatality',
  'feeling of hatred',
  'disease',
  'voter',
  'harmony',
  'sense of peace',
  'violin',
  'nothing',
  'nobody',
  'dictator',
  'human',
  'piece of logic',
  'fate',
  'coin',
  'history',
  'definition',
  'radio',
  'philosophy',
  'reason',
  'wizard',
  'police officer',
  'piece of bread',
  'electron',
  'piece of cheese',
  'glass of milk',
  'cup of coffee',
  'sheep',
  'grain of rice',
  'nugget',
  'piece of gold',
  'diamond',
  'potato',
  'fluid',
  'juice',
  'piece of silver',
  'spoon',
  'regret',
  'uncle',
  'fork',
  'sickness',
  'fluid',
  'reality',
  'moon',
  'comet',
  'liter of gasoline',
  'rocket',
  'bile',
  'carrot',
  'penguin',
  'manager',
  'hospital',
  'board meeting',
  'relationship',
  'apple',
  'molecule of oxygen',
  'molecule of hydrogen',
  'inanimate object',
  'tooth',
  'bead',
  'seed',
  'plant',
  'living thing',
  'animal',
  'egg',
  'neighbor',
  'plate',
  'heart',
  'mist',
  'box',
  'reward',
  'round of golf',
  'number',
  'sin',
  'punishment',
  'government',
  'failure',
  'ghost',
  'distant past',
  'programmer',
  'unrealized dream',
  'ancient history',
  'fragment',
  'realist',
  'absurdity',
  'cobra',
  'list',
  'town',
  'house',
  'board',
  'end',
  'glue container',
  'intangible concept',
  'household object',
  'cablecar',
  'crow',
  'penguin',
  'question',
  'man',
  'Canadian',
  'concept',
  'artist',
  'abstraction',
  'realization',
  'proton',
  'elephant',
  'tree',
  'piece of wood',
  'forest',
  'harness',
  'bridge',
  'city',
  'country',
  'person',
  'idiot',
  'scale',
  'technique',
  'religion',
  'mother',
  'father',
  'party',
  'butterfly',
  'noise',
  'grain',
  'sugar',
  'fish',
  'yeti',
  'idea',
  'meme',
  'quality',
  'revision',
  'desk',
  'late night',
  'book',
  'heaven',
  'hell',
  'blanket',
  'crust',
  'ridge',
  'corporation',
  'bookshelf',
  'bandit',
  'American',
  'European',
  'airplane',
  'knife',
  'ocean',
  'donut',
  'policy',
  'arrow',
  'law',
  'criminal',
  'pyramid',
  'frog',
  'stroke',
  'institution',
  'microscope'
];

const blah = [
  'I have',
  'You have',
  'They have',
  'We have',
  'I have never',
  'You have never',
  'I have never',
  'You have never',
  'Everybody has',
  'Nobody has ever',
  'I might have',
  'You must have',
  'Some people have',
  'I have',
  'You have',
  'They have',
  'We have',
  'Everybody has',
  'Nobody has',
  'Some people have',
  'I have',
  'You have',
  'They have',
  'We have',
  'Everybody has',
  'Nobody has',
  'Some people have',
  'Ideas have',
  'Goats have',
  'Ropes have',
  'Shirts have',
  'Sin has',
  'Chickens have',
  'Dogs have',
  'Cats have',
  'Brains have',
  'It has',
  'Crumbs have',
  'Shadows have',
  'Athletes have',
  'Garbage has',
  'Revolutions have',
  'Wars have',
  'Blood has',
  'Gas has',
  'Hunger has',
  'Ideas have',
  'Hair has',
  'Creation has',
  'Gods have',
  'Men have',
  'Women have',
  'Ducks have',
  'Science has',
  'Policies have',
  'Idiots have',
  'Weather has',
  'Bicycles have',
  'Grapes have',
  'Birds have',
  'Skin has',
  'Concepts have',
  'Music has',
  'Art has',
  'Bile has',
  'Goats have',
  'Kindness has',
  'Mothers have',
  'Fathers have',
  'Solitude has',
  'Regret has',
  'Time has',
  'Stones have',
  'Rock and roll has',
  'Geometry has',
  'Religion has',
  'Mud has',
  'Sand has',
  'Philosophers have',
  'Publishers have',
  'Street lamps have',
  'Reptiles have',
  'Mammals have',
  'Mathematics has',
  'Lanuage has',
  'My sister has',
  'Your brother has',
  'My house has',
  'Your car has',
  'A rainbow has',
  'The kitchen sink has',
  'My intuition has',
  'Beards have',
  'That has',
  'Forests have',
  'The earth has',
  'Peace has',
  'War has',
  'Senility has',
  'Nothing has',
  'Dictators have',
  'Politicians have',
  'Logic has',
  'Riddles have',
  'Definitions have',
  'Perfection has',
  'Noise has',
  'The wind has',
  'Snow has',
  'Rain has',
  'Electricity has',
  'Solitude has',
  'Regret has',
  'Sheep have',
  'I have not',
  'You have not',
  'We have not',
  'They have not',
  'It has not',
  'She has not',
  'He has not',
  'Spoons have',
  'Dreams have',
  'Smoke has',
  'Boats have',
  'Water has',
  'Fish have',
  'Space has',
  'A carrot has',
  'Bosses have',
  'Hospitals have',
  'Board meetings have',
  'Relationships have',
  'Retaliation has',
  'Oxygen has',
  'Carbon has',
  'Objects have',
  'Seeds have',
  'Plants have',
  'Life has',
  'Death has',
  'Moments have',
  'Tires have',
  'Eggs have',
  'Humidity has',
  'Prisoners have',
  'Animals have',
  'The universe has',
  'Ghosts have',
  'Songs have',
  'Streets have',
  'Love has',
  'Hate has',
  'Success has',
  'Wishes have',
  'Opinions have',
  'Exhaustion has',
  'Cities have',
  'Heaven has',
  'Hell has',
  'Bridges have',
  'Windows have',
  'Everything has',
  'People have',
  'Techniques have',
  'Educators have',
  'Receipts have',
  'Ponies have',
  'Fear has',
  'The internet has',
  'Late nights have',
  'Corporations have',
  'Bookshelves have',
  'America has',
  'Airplanes have',
  'Knives has',
  'Donuts have',
  'Police have',
  'Spiders have',
  'Ovens have'
];
const kakobunshi = [
  'seen',
  'kissed',
  'electrocuted',
  'crushed',
  'saved',
  'smashed',
  'spilled',
  'cured',
  'wresteled',
  'faught',
  'hit',
  'jumped on',
  'shot',
  'referenced',
  'hugged',
  'killed',
  'touched',
  'looked at',
  'polished',
  'betrayed',
  'stolen',
  'fed',
  'given a massage to',
  'removed',
  'spat upon',
  'yelled at',
  'stood upon',
  'boiled',
  'punched',
  'described',
  'soiled',
  'feasted upon',
  'returned',
  'disposed of',
  'thrown away',
  'kicked',
  'stepped on',
  'sniffed',
  'leaked',
  'dropped',
  'thrown',
  'thrown up',
  'smelled',
  'met',
  'interviewed',
  'called',
  'bought',
  'heard',
  'produced',
  'been in love with',
  'stabbed',
  'burned',
  'eaten',
  'ground up',
  'cut up',
  'laughed at',
  'sung about',
  'demanded',
  'requested',
  'tasted',
  'loved',
  'talked about',
  'been with',
  'written about',
  'heard of',
  'flown',
  'grown',
  'hidden',
  'chosen',
  'sought',
  'walked with',
  'made',
  'been seen with',
  'had breakfast with',
  'had lunch with',
  'sat on',
  'slept on',
  'slept with',
  'been near',
  'been with',
  'been told about',
  'driven',
  'received',
  'gotten',
  'become',
  'swam with',
  'cried about',
  'lusted after',
  'thought about',
  'bled',
  'bitten',
  'caught',
  'taught',
  'drawn',
  'felt',
  'sued',
  'fought with',
  'witnessed',
  'frozen'
];
